F.module("mancard:subscribe/subscribe",function(require,exports,ctx){var cardCollection=require("mancard:skeleton/card_collection");var SubDom=["s_ctner_contents"],isSubscribe=false,actItem,aniStarNode=$('<div class="sub-anistar"><b></b></div>'),aniPicNode=$('<div class="sub-anipic">                            <div class="sub-ie-mask"></div>                        </div>'),aniStarNodes=[],aniAddNode=$('<div class="sub-aniadd"></div>'),aniStarAddNode=$('<div class="sub-anistaradd"></div>'),
bodyNode=$("#head"),submitURL=s_domain.baseuri+"/subscribe/submit/manoperation ",DATA_HOOK="data-subscribe",DATA_RID="data-rid",DATA_SUBPARAM="data-subparam",count=0;var Tips=require("superui:component/tips");var bindEvent=function(item){$("#"+item).on("mouseenter mouseleave","["+DATA_HOOK+"]",function(e){var t=e.target;if(e.type==="mouseenter"){window.debugenter=function(){var curSubNode;if((curSubNode=$(this).find(".subscribe"))[0]){curSubNode.show();if($(this).attr(DATA_HOOK)=="1"){
_resetSubNode("1",curSubNode)}else{_resetSubNode("0",curSubNode)}return}var subNode=$('<div class="subscribe" data-click="LOG_BTN_SUB"><div class="sub"><em class="sub-bg"></em><b class="sub-star"></b><span class="sub-txt" style="display:none">已关注</span></div></div>');if($(this).attr(DATA_HOOK)=="1"){_resetSubNode("1",subNode)}else{_resetSubNode("0",subNode)}if($(this).find(".sub-contaniner").length>0){$(this).find(".sub-contaniner").append(subNode)}else{$(this).append(subNode)}if($.isIE6){
subNode.css("zoom","1")}};window.debugenter.call(this)}else{if(e.target!=$(this).find(".subscribe").find(".sub-star")[0]){$(this).find(".subscribe").css("zoom","0").detach()}}}).on("click",".subscribe",function(e){onSubscribe($(this),$(this));e.stopPropagation()})};var _resetSubNode=function(st,subNode){var subClassNode=subNode.children();if(st=="1"){subClassNode.removeClass("unsub");subClassNode.addClass("sub");subNode.attr("data-click","LOG_BTN_UNSUB");subNode.find(".sub-txt").text("已关注");if(
s_session.curmod=="20"){subNode.attr("title","已关注,点击取消")}}else if(st=="0"){subClassNode.removeClass("sub");subClassNode.addClass("unsub");subNode.attr("data-click","LOG_BTN_SUB");subNode.find(".sub-txt").text("关注");if(s_session.curmod=="20"){subNode.attr("title","添加到关注")}}};var onSubscribe=function(t,subNode){var node=t,actItem=node.parents("["+DATA_HOOK+"]"),subData=actItem.attr(DATA_HOOK),rId=actItem.attr(DATA_RID),subParam=actItem.attr(DATA_SUBPARAM),actName,defaultParam={id:rId};if(subParam
){var regx=/([^:]+):([^;]+);/gi,regResult;while(regResult=regx.exec(subParam)){defaultParam[regResult[1]]=regResult[2]}}if(subData=="1"){actName="del";defaultParam.cmd=actName;subDel(actItem,defaultParam,function(){actItem.attr(DATA_HOOK,"0");_resetSubNode("0",subNode)})}else{actName="add";defaultParam.cmd=actName;subAdd(actItem,defaultParam,function(){actItem.attr(DATA_HOOK,"1");_resetSubNode("1",subNode)})}actItem.parents(".s-xmancard").attr("data-subChange",1)};function subAdd(actItem,param,
cb){var pos=actItem.offset();var toPos=$("#s_menu_mine .mine-icon").offset();var a=aniPicNode.clone();a.attr("class","sub-anipic sub-anipic-"+s_session.curmod);var imgSrc=actItem.closest("["+DATA_RID+"]").find("img").attr("src");var reqParam={tabid:window.s_session.curmod,url:actItem.find("a").attr("href")||"",name:actItem.find("a").attr("title")||"",from:window.s_session.curmod};$.extend(reqParam,param);$.ajaxpost(submitURL,reqParam,function(response){var result=response.errNo;if(
result=="0"||result=="6004"){cb&&cb();ctx.fire("refresh",{tabid:reqParam.tabid,param:reqParam,response:response,actItem:actItem});if($.isIE6){return}if($.isIE&&$.browser.ie<9&&s_session.userSkinOpacity>20){a.css({filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod=scale, src='"+imgSrc+"')"})}else{a.css({"background-image":"url("+imgSrc+")"});a.css({filter:"none"})}setTimeout(function(){toPos=$("#s_menu_mine .mine-icon").offset();var tolerance=-parseInt($(
"#s_menu_gurd").css("margin-top"),10);a.animate({left:toPos.left-10+"px",top:toPos.top-7+tolerance+"px"},1e3,function(){a.fadeOut(function(){a.remove()});var startNode=aniStarAddNode.clone();startNode.css({left:toPos.left,top:toPos.top});bodyNode.append(startNode);startNode.show();startNode.animate({top:toPos.top-40,opacity:"0"},2e3,function(e){startNode.remove()})})},0);a.css({left:pos.left+45,top:pos.top});bodyNode.append(a);if(cardCollection.options("menuStatus")=="2"||cardCollection.options(
"menuStatus")=="1"){F.call("mancard:skeleton/presenter","forceMenu")}}else if(result=="501"){ctx.fire("showExceedTips",{tabid:reqParam.tabid})}else{}})}function subDel(actItem,param,cb){var reqParam={tabid:window.s_session.curmod,url:actItem.find("a").attr("href")||"",name:actItem.find("a").attr("title")||"",from:window.s_session.curmod};$.extend(reqParam,param);$.ajaxpost(submitURL,reqParam,function(response){var result=response.errNo;if(result=="0"){cb&&cb();setTimeout(function(){ctx.fire(
"refresh",{tabid:reqParam.tabid,param:reqParam,response:response,actItem:actItem})},1e3)}else{}})}exports.init=function(){$.each(SubDom,function(i,e){bindEvent(e)})};exports.subAdd=subAdd;exports.subDel=subDel});F.call("mancard:subscribe/subscribe","init");